/**
 * Content calendar scheduled posts: find due items and enqueue content_calendar_post jobs.
 * Run daily (e.g. 8 AM) so that "today's" calendar day gets a blog post generated by the worker.
 */

import {
  getDueContentCalendarItems,
  claimContentCalendarSlot
} from '../services/content-calendar-service.js';
import { createJob } from '../services/job-queue.js';

/**
 * Find audiences with a content calendar item due today (by subscription + content_calendar_generated_at),
 * claim each slot, and enqueue one content_calendar_post job per claimed slot.
 * Safe to run multiple times; only unclaimed slots are enqueued.
 *
 * @returns {{ enqueued: number, due: number, errors: string[] }}
 */
export async function processContentCalendarScheduledPosts() {
  const errors = [];
  let due = 0;
  let enqueued = 0;

  try {
    const items = await getDueContentCalendarItems();
    due = items.length;

    for (const { audienceId, dayNumber, userId } of items) {
      try {
        const claimed = await claimContentCalendarSlot(audienceId, dayNumber);
        if (!claimed) continue;

        const result = await createJob(
          'content_calendar_post',
          { audienceId, dayNumber },
          { userId, sessionId: null, tenantId: null }
        );
        if (result?.jobId) {
          enqueued++;
          console.log(`📅 [content-calendar-scheduler] Enqueued post for audience ${audienceId} day ${dayNumber} (job ${result.jobId})`);
        }
      } catch (err) {
        const msg = err?.message || String(err);
        errors.push(`audience ${audienceId} day ${dayNumber}: ${msg}`);
        console.warn(`📅 [content-calendar-scheduler] Failed to enqueue:`, msg);
      }
    }

    if (due > 0 || enqueued > 0) {
      console.log(`📅 [content-calendar-scheduler] Due: ${due}, enqueued: ${enqueued}, errors: ${errors.length}`);
    }
  } catch (err) {
    console.error('❌ [content-calendar-scheduler]', err?.message || err);
    errors.push(err?.message || String(err));
  }

  return { enqueued, due, errors };
}

export default {
  processContentCalendarScheduledPosts
};
